addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

env:
  - CHEF_LICENSE=accept
        
before_script:
- eval "$(chef shell-init bash)"
- chef --version
script:
- chef exec rspec
- kitchen verify